//! Phase 7a-ii integration tests: `read_book` end to end over committed
//! fixtures (regenerated by `cargo run -p conservatory-audiobooks --example
//! gen_fixtures`). The pure logic is unit-tested in each module; these exercise
//! the orchestration (collect → tags → sidecar → folder → merge → chapters).

use std::path::PathBuf;

use conservatory_audiobooks::ffprobe::ffprobe_available;
use conservatory_audiobooks::read_book;

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(rel)
}

#[test]
fn multi_file_book_reads_one_chapter_per_file() {
    let draft = read_book(&fixture("multi/Test Author/Test Book")).unwrap();

    assert_eq!(draft.title.as_deref(), Some("Test Book"));
    assert_eq!(draft.authors.len(), 1);
    assert_eq!(draft.authors[0].name, "Test Author");
    // Person sort names are Last-First (not the music article-move).
    assert_eq!(draft.authors[0].sort_name, "Author, Test");
    assert_eq!(draft.narrators.len(), 1);
    assert_eq!(draft.narrators[0].name, "Test Reader");
    assert_eq!(draft.year, Some(2021));

    assert_eq!(draft.chapters.len(), 2);
    assert_eq!(draft.chapters[0].idx, 0);
    assert_eq!(draft.chapters[0].file_offset, 0.0);
    assert_eq!(draft.chapters[0].title.as_deref(), Some("Chapter One"));
    assert_eq!(draft.chapters[1].idx, 1);
    assert_eq!(draft.chapters[1].title.as_deref(), Some("Chapter Two"));
    // Each chapter points at its own source file.
    assert!(draft.chapters[0].file_path.ends_with("01.mp3"));
    assert!(draft.chapters[1].file_path.ends_with("02.mp3"));
}

#[test]
fn single_m4b_embedded_chapters() {
    // The embedded-chapter path needs ffprobe; skip cleanly without it (the
    // rsgain test precedent), so CI without ffmpeg still passes.
    if !ffprobe_available() {
        eprintln!("ffprobe not available; skipping embedded-chapter test");
        return;
    }
    let draft = read_book(&fixture("single/book.m4b")).unwrap();

    assert_eq!(draft.chapters.len(), 2, "two embedded chapters");
    assert_eq!(draft.chapters[0].idx, 0);
    assert_eq!(draft.chapters[0].file_offset, 0.0);
    assert_eq!(draft.chapters[0].title.as_deref(), Some("First Chapter"));
    assert!((draft.chapters[0].duration.unwrap() - 2.0).abs() < 0.2);
    assert_eq!(draft.chapters[1].file_offset, 2.0);
    assert_eq!(draft.chapters[1].title.as_deref(), Some("Second Chapter"));
    // Both chapters address spans inside the one file.
    assert!(draft.chapters[0].file_path.ends_with("book.m4b"));
    assert!(draft.chapters[1].file_path.ends_with("book.m4b"));
}

#[test]
fn sidecar_overrides_embedded_tags() {
    // The folder carries an embedded "Embedded *" tag set and a metadata.opf
    // with "Sidecar *"; the sidecar wins every contested field.
    let draft = read_book(&fixture("sidecar/Tagged Folder")).unwrap();

    assert_eq!(draft.title.as_deref(), Some("Sidecar Title"));
    assert_eq!(draft.authors.len(), 1);
    assert_eq!(draft.authors[0].name, "Sidecar Author");
    assert_eq!(draft.narrators[0].name, "Sidecar Reader");
    assert_eq!(draft.series.as_deref(), Some("Sidecar Series"));
    assert_eq!(draft.series_sequence, Some(2.5));
}
