//! Phase 1c integration tests: read committed audio fixtures of each format.
//!
//! The fixtures under `tests/fixtures/audio/` are regenerated by
//! `cargo run -p conservatory-core --example gen_audio_fixtures` (ffmpeg +
//! lofty). They carry an identical known tag set and an embedded solid-red
//! cover; assertions below match what each container format actually preserves.

use std::path::PathBuf;

use conservatory_core::{compute_accent, find_cover_bytes, read_track};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/audio")
        .join(name)
}

/// Fields every format preserves identically.
fn assert_common_fields(name: &str) {
    let draft = read_track(&fixture(name)).expect("reading fixture");
    assert_eq!(draft.title.as_deref(), Some("Test Title"), "{name} title");
    assert_eq!(
        draft.artist.as_deref(),
        Some("Test Artist"),
        "{name} artist"
    );
    assert_eq!(
        draft.album_artist.as_deref(),
        Some("Test Album Artist"),
        "{name} album artist"
    );
    assert_eq!(draft.album.as_deref(), Some("Test Album"), "{name} album");
    assert_eq!(draft.track_no, Some(3), "{name} track no");
    assert_eq!(draft.track_total, Some(12), "{name} track total");
    assert_eq!(draft.disc_no, Some(1), "{name} disc no");
    assert_eq!(draft.year, Some(2021), "{name} year");
    assert_eq!(draft.replaygain_track, Some(-7.5), "{name} rg track");
    assert_eq!(draft.replaygain_album, Some(-7.2), "{name} rg album");
    assert!(draft.bitrate.is_some_and(|b| b > 0), "{name} bitrate");
    // Encoders pad the 0.3s source slightly; assert presence and a loose range.
    let dur = draft.duration.expect("duration");
    assert!((0.2..0.6).contains(&dur), "{name} duration {dur}");
}

#[test]
fn reads_all_formats_common_fields() {
    for name in ["sample.flac", "sample.mp3", "sample.opus", "sample.m4a"] {
        assert_common_fields(name);
    }
}

#[test]
fn vorbis_and_mp4_keep_multi_value_genres() {
    // Vorbis comments (flac/opus) and MP4 ilst preserve both genre values.
    for name in ["sample.flac", "sample.opus", "sample.m4a"] {
        let draft = read_track(&fixture(name)).expect("reading fixture");
        assert_eq!(draft.genres, vec!["Electronic", "Ambient"], "{name} genres");
    }
}

#[test]
fn id3v2_collapses_to_a_single_genre() {
    // ID3v2 stores a single genre value; the reader returns it verbatim. This
    // pins the format quirk rather than papering over it.
    let draft = read_track(&fixture("sample.mp3")).expect("reading fixture");
    assert_eq!(draft.genres, vec!["Ambient"]);
}

#[test]
fn opus_reports_48khz_others_44_1() {
    // Opus always decodes at 48 kHz; the rest keep the 44.1 kHz source rate.
    let opus = read_track(&fixture("sample.opus")).unwrap();
    assert_eq!(opus.sample_rate, Some(48_000));
    for name in ["sample.flac", "sample.mp3", "sample.m4a"] {
        assert_eq!(
            read_track(&fixture(name)).unwrap().sample_rate,
            Some(44_100),
            "{name}"
        );
    }
}

#[test]
fn embedded_cover_accent_is_red() {
    // The flac fixture embeds a solid-red 32x32 PNG; the accent must be red.
    let draft = read_track(&fixture("sample.flac")).expect("reading fixture");
    assert!(draft.cover.is_some(), "expected an embedded cover");
    let bytes = find_cover_bytes(&fixture("sample.flac"), &draft).expect("cover bytes");
    assert_eq!(compute_accent(&bytes).unwrap(), 0xFF0000);
}
